apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: my wonderful app
  labels:
    application: myapp
    size: medium
    team: team-a
    environment: qa
  name: myapp-qa